# Databricks notebook source

# COMMAND ----------

# MAGIC %pip install databricks-vectorsearch
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

dbutils.widgets.text("catalog", "hiroshi", "カタログ名")
dbutils.widgets.text("schema", "ai_demo_hub", "スキーマ名")
dbutils.widgets.text("table", "demos", "テーブル名")
dbutils.widgets.text("vs_endpoint", "one-env-shared-endpoint-1", "Vector Search エンドポイント名")
dbutils.widgets.text("embedding_endpoint", "databricks-gte-large-en", "エンベディングモデル エンドポイント名")
dbutils.widgets.dropdown("pipeline_type", "CONTINUOUS", ["CONTINUOUS", "TRIGGERED"], "VS パイプラインタイプ")
dbutils.widgets.text("primary_key", "demo_id", "主キー列")
dbutils.widgets.text("embedding_source_column", "all_info_md", "エンベディング対象列")

# COMMAND ----------

catalog = dbutils.widgets.get("catalog")
schema = dbutils.widgets.get("schema")
table = dbutils.widgets.get("table")
vs_endpoint = dbutils.widgets.get("vs_endpoint")
embedding_endpoint = dbutils.widgets.get("embedding_endpoint")
pipeline_type = dbutils.widgets.get("pipeline_type")
primary_key = dbutils.widgets.get("primary_key")
embedding_source_column = dbutils.widgets.get("embedding_source_column")

source_table = f"{catalog}.{schema}.{table}"
vs_index = f"{catalog}.{schema}.{table}_vs_index"

# COMMAND ----------

spark.sql(f"""
CREATE CATALOG IF NOT EXISTS {catalog}
""")

spark.sql(f"""
CREATE SCHEMA IF NOT EXISTS {catalog}.{schema}
""")

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {source_table} (
  -- 自動採番 PK (IDENTITY)
  demo_id BIGINT GENERATED BY DEFAULT AS IDENTITY
          COMMENT '自動採番 ID',

  /* ===== 基本情報 ===== */
  title          STRING  NOT NULL COMMENT 'デモのタイトル',
  summary        STRING           COMMENT 'カード表示用の要約',
  description_md STRING           COMMENT '詳細説明 (Markdown)',

  /* ===== 投稿者・日時 ===== */
  creator_emp_id STRING  COMMENT 'デモの作成者の社員ID',
  owner_emp_id   STRING  NOT NULL COMMENT '代表投稿者の社員ID',
  created_at     TIMESTAMP NOT NULL DEFAULT current_timestamp()
                 COMMENT '登録日時',
  updated_at     TIMESTAMP         COMMENT '最終編集日時',

  /* ===== ステータス ===== */
  status         STRING  NOT NULL COMMENT 'draft / in_review / published / archived',

  /* ===== リンク ===== */
  demo_url       STRING  NOT NULL COMMENT '実デモ URL',
  repo_url       STRING           COMMENT 'ソースコードリポジトリ',

  /* ===== 技術スタック ===== */
  products       ARRAY<STRING> NOT NULL COMMENT '利用製品名の配列',

  /* ===== ガバナンス ===== */
  confidentiality STRING COMMENT 'public / internal',

  remarks        STRING COMMENT '備考',
  all_info_md        STRING COMMENT 'すべての情報をマークダウン形式で記述',

  /* ===== 制約 ===== */
  CONSTRAINT demos_pk PRIMARY KEY (demo_id)
)
USING DELTA
PARTITIONED BY (status)
TBLPROPERTIES (
  delta.feature.allowColumnDefaults = 'supported',
  delta.feature.identityColumns     = 'supported',
  delta.columnMapping.mode          = 'name',
  delta.enableChangeDataFeed        = true,
  delta.logRetentionDuration        = 'interval 30 days'
)
COMMENT '社内 AI デモのメタデータカタログ'
""")

# COMMAND ----------

spark.sql(f"""
ALTER TABLE {source_table}
  ADD CONSTRAINT status_chk CHECK (status IN ('draft','in_review','published','archived'))
""")

spark.sql(f"""
ALTER TABLE {source_table}
  ADD CONSTRAINT conf_chk CHECK (confidentiality IN ('public','internal'))
""")

# COMMAND ----------

from databricks.vector_search.client import VectorSearchClient

vsc = VectorSearchClient()

if vs_endpoint not in [e['name'] for e in vsc.list_endpoints().get('endpoints', [])]:
    vsc.create_endpoint_and_wait(name=vs_endpoint, endpoint_type="STANDARD")

print(f"Endpoint named {vs_endpoint} is ready.")

# COMMAND ----------

try:
  vsc.get_index(vs_endpoint, vs_index)
except Exception:
  print(f"Creating index {vs_index} on endpoint {vs_endpoint}...")
  vsc.create_delta_sync_index_and_wait(
    endpoint_name=vs_endpoint,
    index_name=vs_index,
    pipeline_type=pipeline_type,
    source_table_name=source_table,
    primary_key=primary_key,
    embedding_source_column=embedding_source_column,
    embedding_model_endpoint_name=embedding_endpoint
  )

  print(f"index {vs_index} on table {source_table} is ready")
